name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - dvc==2.10
  - fastapi==0.63
  - git=2.30
  - gunicorn==20.1
  - jupyter==1.0
  - jupyterlab=3.0
  - numpy==1.22
  - pip=20.3
  - pandas==1.2
  - pytest==7.1
  - requests==2.27
  - scikit-learn==1.1
  - uvicorn==0.17